# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, confusion_matrix


# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [4]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
# ___ = pd_read_csv("___.csv")


# Load the CSV file
df = pd.read_csv('data_clustering.csv')




In [5]:
# Tampilkan 5 baris pertama dengan function head.

df.head()

TransactionAmount  PreviousTransactionDate  TransactionType  Location  \
0          -0.970013                      680                1        36   
1           0.268442                     1178                1        15   
2          -0.586320                     1262                1        23   
3          -0.387257                      818                1        33   
4          -0.703069                      635                1        28   

   Channel  CustomerAge  CustomerOccupation  TransactionDuration  \
0        0     1.423244                   0            -0.550895   
1        0     1.310979                   0             0.306614   
2        2    -1.439513                   3            -0.908191   
3        2    -1.046586                   3            -1.351238   
4        0    -1.495646                   3             0.749661   

   LoginAttempts  AccountBalance  TransactionDate  Target  
0      -0.205525       -0.001359              105       1  
1      -0.205525        2.217583              192       2  
2      -0.205525       -1.025249               41       2  
3      -0.205525        0.885748              163       1  
4      -0.205525       -1.112673               13       1

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [10]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

# Pisahkan fitur dan target
X = df.drop(columns=['Target'])
y = df['Target']

# Lakukan pembagian 80% data latih dan 20% data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [11]:
# Buatlah model klasifikasi menggunakan Decision Tree

# 1. Inisialisasi model
model = DecisionTreeClassifier(random_state=42)

# 2. Latih model menggunakan data latih
model.fit(X_train, y_train)

# 3. Prediksi menggunakan data uji
y_pred = model.predict(X_test)

# 4. Evaluasi model
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Akurasi: 0.9979166666666667

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00       157
           1       1.00      1.00      1.00       167
           2       0.99      1.00      1.00       156

    accuracy                           1.00       480
   macro avg       1.00      1.00      1.00       480
weighted avg       1.00      1.00      1.00       480


Confusion Matrix:
 [[156   0   1]
 [  0 167   0]
 [  0   0 156]]


In [12]:
# Menyimpan Model
# import joblib
# joblib.dump(model, 'decision_tree_model.h5')

import joblib
joblib.dump(model, 'decision_tree_model.h5')


['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [ ]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

In [ ]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [13]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

# Hyperparameter Tuning: Decision Tree
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Define parameter grid untuk tuning
param_grid = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}

# Inisialisasi model dasar
dt = DecisionTreeClassifier(random_state=42)

# Grid Search untuk mencari kombinasi terbaik
grid_search = GridSearchCV(estimator=dt, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Ambil model terbaik
best_model = grid_search.best_estimator_

# Prediksi dengan model hasil tuning
y_pred_tuned = best_model.predict(X_test)



In [14]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

# Evaluasi hasil tuning
print("Akurasi setelah tuning:", accuracy_score(y_test, y_pred_tuned))
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_tuned))



Akurasi setelah tuning: 0.9979166666666667

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00       157
           1       1.00      1.00      1.00       167
           2       0.99      1.00      1.00       156

    accuracy                           1.00       480
   macro avg       1.00      1.00      1.00       480
weighted avg       1.00      1.00      1.00       480


Confusion Matrix:
 [[156   0   1]
 [  0 167   0]
 [  0   0 156]]


In [15]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')

# Simpan model hasil tuning
joblib.dump(best_model, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code